### ISSUE TITLE
Is all USB ports working?

### ISSUE THREAD

**Issue by mukhtharcm** [DobbyAkhmadi/Lenovo-X260-Opencore-EFI-Monterey#1]
I recently bought a Thinkpad x260 and I used [this]( https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore ) guide for Hackintosh.
But my left side USB ports are not working and I think the battery status shown isn't correct.

Do all the USB Ports work in this build?

Do you have a guide or something?

Thanks in advance

**Comment by DobbyAkhmadi** [comment]
yes all usb worked well, I still use this laptop
